### PR TITLE
[Fixes AB#813] imgproxy integration

### PR DESCRIPTION
**Pull request by mightymatth**

### CODE REVIEW

**Comment by githinho** [comment]
Warning: Running a server with --disable-host-check is a security risk. See https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a for more information.

**Comment by githinho** [comment]
Strange stuff in Safari:
image

**Comment by githinho** [comment]
Also from Safar:
`Refused to execute http://localhost:4200/assets/env.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.
http://localhost:4200/api/user/public/app/config/hostname/localhost`

**Comment by mightymatth** [comment]
> Warning: Running a server with --disable-host-check is a security risk. See https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a for more information.

Don't worry, it's just for the development when you want to share a running server with someone else, outside of your network. As we run nothing security-sensitive while developing, there is no security risk. That's how I see it.

--- 

Marked posts with 🚀 icon are fixed in one way or another.

**Review by githinho — APPROVED** [review]

**Review by githinho — DISMISSED** [review]

**Review by githinho — APPROVED** [review]

**Pull request merged**
