### PR TITLE
[Fixes AB#703] Redesign manage payments tab

### PR DESCRIPTION
**Pull request by Skafec**
What was done:

- Removed unnecessary project observable and method to get observable data from manage payments component
- Removed observable in template
- Removed manage payments route in app-router
- Changed Revenue share logic so that we get navigated to edit project screen after successful revenue share payout (we could implement static success screen here so that user knows everything went OK but we do have popup)
- Removed manage_payments from project deposit, withdraw and revenue share in manage payments component and app-router
- Changed Deposit/Withdraw component logic to use routerLink to navigate back
- Added new design to manage payments tab
- Reduced margins below tabs in edit project screen

@mightymatth I thought that it would be better if we used one new global variable in Deposit/Withdraw screens for the organization ID. That way we can use routerLink to navigate back instead of using the method. What do you think?

### CODE REVIEW

**Comment by mj-ampnet** [comment]
Screenshot 2020-12-16 at 12 51 15
Izlgeda dobro, ovaj popup se raspada jedino

**Comment by mj-ampnet** [comment]
@Skafec i see it's been fixed in other branch, ignore my comment

**Review by mightymatth — APPROVED** [review]
It's OK for now, but it's better to have this approach: 
"If you have tabs on screen, it's very likely that you need their own routes."

For example, on the manage payments screen, I would make a separate route for details, news and share payout.

projects/:id/details
projects/:id/news
projects/:id/manage_payments

this way, when you are on manage payments, you click on deposit, and you return back, you will be returned back to manage payments. In solution we have now, this is not the case. another thing is that it's easier to maintain logic on 3 separate screens than on a single one.

we'll make it in the future, it's fine.

**Review by mightymatth — COMMENTED** [review]
Ready for QA.

**Review by mightymatth — APPROVED** [review]

**Pull request merged**
